### ISSUE TITLE
[BUG]: After adding an extra array to an existing configuration, the new array isn't discovered via the proxy

### ISSUE THREAD

**Issue by coulof** [dell/karavi-authorization#85]
**Describe the bug**
After adding a new array to an existing configuration, and injection of the karavi patch the new array isn't probed:
```
REP 5660: rpc error: code = FailedPrecondition desc = System 4d4a2e5a36080e0f has not been probed"
```

**To Reproduce**

1. The starting point is karavi-authorization has one or more arrays discovered
2. We add a new array to the secret
3. We inject the patch with : `kubectl get secrets,deployments,daemonsets -n powerflex -o yaml | karavictl inject  --image-addr docker.io/coulof/sidecar-proxy:v0.1.0  --proxy-host lgloxxxx.lss.emc.com  --insecure=true`

After `karavictl inject` we can see that the `intendedEnpoint` & `endpoint` are present and up to date in every entry of the secret but the `karavi-authorization-proxy` sidecar misses that new service.

To solve it we had to force the rollout with `kubectl rollout restart -n powerflex deployment/vxflexos-controller` 

**Expected behavior**
The `karavictl inject` should have restart the sidecar automatically.

**System Information (please complete the following information):**

- OS/Version: SLES15SP2
- Kubernetes Version 1.20.5

**Comment by ioeicicdsvc** [comment]
@coulof: Thank you for submitting this issue!

The issue is currently awaiting triage. Please make sure you have given us as much context as possible.

If the maintainers determine this is a relevant issue, they will remove the needs-triage label and assign an appropriate priority label.

------------------------------------------------------------------------------------------------------------------------
We want your feedback! If you have any questions or suggestions regarding our contributing process/workflow, please reach out to us at karavi@dell.com.

**Comment by alikdell** [comment]
sync

**Comment by ioeicicdsvc** [comment]
link: 3217
