### ISSUE TITLE
[BUG]: Update RPM name to include the next release version

### ISSUE THREAD

**Issue by tdawe** [dell/karavi-authorization#95]
**Describe the bug**
Building the RPM creates a file with name `karavi-authorization-0.1-0.x86_64.rpm`. The RPM spec should be updated to include the next release version.

**To Reproduce**

1. Build the RPM and view the file name.

**Expected behavior**

**Screenshots**

**Logs**
If applicable, submit logs or stack traces from the affected services

**System Information (please complete the following information):**

- OS/Version: [e.g. RHEL 7.6]
- Kubernetes Version [e.g. 1.18]
- Additional Information...

**Additional context**

**Comment by ioeicicdsvc** [comment]
@tdawe: Thank you for submitting this issue!

The issue is currently awaiting triage. Please make sure you have given us as much context as possible.

If the maintainers determine this is a relevant issue, they will remove the needs-triage label and assign an appropriate priority label.

------------------------------------------------------------------------------------------------------------------------
We want your feedback! If you have any questions or suggestions regarding our contributing process/workflow, please reach out to us at karavi@dell.com.
